// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


// await Firebase.initializeApp(
// options: DefaultFirebaseOptions.currentPlatform,
// );
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCk12JmiDSbspIAqMbYDozk6qZkIW2tzc',
    appId: '1:248845571960:android:eed04369d9de7fe7931a8d',
    messagingSenderId: '248845571960',
    projectId: 'easy-upload-f3ee6',
    storageBucket: 'easy-upload-f3ee6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV5UvlYes3jAXt2gFH8-B-o9BJ-tZ6qGg',
    appId: '1:248845571960:ios:20637e9498d10416931a8d',
    messagingSenderId: '248845571960',
    projectId: 'easy-upload-f3ee6',
    storageBucket: 'easy-upload-f3ee6.firebasestorage.app',
    iosBundleId: 'com.example.easyUpload',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM0PxmiXWTZVkmERqAmcEXvt2_dVCEH5o',
    appId: '1:248845571960:web:fa5ceda09ae7449f931a8d',
    messagingSenderId: '248845571960',
    projectId: 'easy-upload-f3ee6',
    authDomain: 'easy-upload-f3ee6.firebaseapp.com',
    storageBucket: 'easy-upload-f3ee6.firebasestorage.app',
    measurementId: 'G-79PP1F8MRN',
  );

}